// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bpmlmyypggjvqjikyhpk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJwbWxteXlwZ2dqdnFqaWt5aHBrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3Mzg1ODAsImV4cCI6MjA2MDMxNDU4MH0.g4U6jaERgJh8kdW9jiAW5zrNLw968jHEEUQpVuJPe-Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);